import { clean, normalizeCommand, normalizeName } from '../utils/text.js';
import { getUserPoints, changeUserPoints } from '../services/gamePoints.service.js';
import { createBankDeposit, getBankAccount, withdrawReadyBankDeposits, getBankCooldownSeconds } from '../services/bankGame.service.js';
const bankCooldownMap=new Map();
function parseBankCommand(text){const raw=clean(text);const c=normalizeCommand(raw);const en=raw.match(/^bank\s*@?\s*(\d+)$/i);if(en)return{isCommand:true,lang:'en',action:'deposit',amount:Number(en[1])||0};const ar=raw.match(/^بنك\s*@?\s*(\d+)$/i);if(ar)return{isCommand:true,lang:'ar',action:'deposit',amount:Number(ar[1])||0};if(c==='bank')return{isCommand:true,lang:'en',action:'status',amount:0};if(c==='بنك')return{isCommand:true,lang:'ar',action:'status',amount:0};if(c==='bankwithdraw')return{isCommand:true,lang:'en',action:'withdraw',amount:0};if(c==='بنكسحب')return{isCommand:true,lang:'ar',action:'withdraw',amount:0};return{isCommand:false,lang:'en',action:'',amount:0};}
function getPlayerKey(m){return clean(m.fromUsername)||clean(m.fromUserId)||'';}function getCooldownKey(m){return clean(m.fromUserId)||normalizeName(m.fromUsername);}function fmt(ms,lang='en'){const t=Math.max(0,Math.ceil(ms/1000));const m=Math.floor(t/60);const s=t%60;if(lang==='ar')return m<=0?`${s} ثانية`:`${m} دقيقة و ${s} ثانية`;return m<=0?`${s}s`:`${m}m ${s}s`;}
async function cooldown(m){const key=getCooldownKey(m);if(!key)return{allowed:false,remainingMs:0};const ms=(await getBankCooldownSeconds())*1000;const now=Date.now();const old=bankCooldownMap.get(key)||0;if(now-old<ms)return{allowed:false,remainingMs:ms-(now-old)};bankCooldownMap.set(key,now);return{allowed:true,remainingMs:0};}
function statusText({account,lang}){const active=(account.deposits||[]).filter(d=>d.withdrawn!==true);if(active.length===0)return lang==='ar'?'🏦 لا توجد ودائع في البنك.':'🏦 No active bank deposits.';const lines=active.slice(0,5).map((d,i)=>{const ready=Date.parse(d.readyAt)<=Date.now();return lang==='ar'?`${i+1}. ${d.amount} + ${d.profit} = ${d.total} ${ready?'جاهزة':'غير جاهزة'}`:`${i+1}. ${d.amount} + ${d.profit} = ${d.total} ${ready?'ready':'not ready'}`});return lang==='ar'?['🏦 ودائعك:',...lines,'','اكتب: بنك سحب'].join('\n'):['🏦 Your deposits:',...lines,'','Type: bank withdraw'].join('\n');}
export async function handleBankCommand({roomMessage,ws,targetRoomId,targetRoomName}){const p=parseBankCommand(roomMessage.text);if(!p.isCommand)return false;const lang=p.lang;const user=getPlayerKey(roomMessage);const name=clean(roomMessage.fromUsername)||clean(roomMessage.fromUserId)||'User';if(!user){ws.sendRoomMessage(targetRoomId,lang==='ar'?'❌ لم أستطع تحديد اللاعب.':'❌ Could not identify player.',targetRoomName);return true;}if(p.action==='status'){const account=await getBankAccount(user);ws.sendRoomMessage(targetRoomId,statusText({account,lang}),targetRoomName);return true;}if(p.action==='withdraw'){const r=await withdrawReadyBankDeposits(user);if(!r.ok){ws.sendRoomMessage(targetRoomId,lang==='ar'?`❌ فشل السحب. السبب: ${r.reason}`:`❌ Withdraw failed. Reason: ${r.reason}`,targetRoomName);return true;}if(r.amount<=0){ws.sendRoomMessage(targetRoomId,lang==='ar'?'🏦 لا توجد ودائع جاهزة للسحب.':'🏦 No ready deposits to withdraw.',targetRoomName);return true;}await changeUserPoints(user,r.amount);const f=await getUserPoints(user);ws.sendRoomMessage(targetRoomId,lang==='ar'?[`🏦 ${name} سحب من البنك!`,`✅ حصلت على ${r.amount} نقطة.`,`💰 نقاطك: ${f}`].join('\n'):[`🏦 ${name} withdrew from the bank!`,`✅ received ${r.amount} points.`,`💰 your points: ${f}`].join('\n'),targetRoomName);return true;}const cd=await cooldown(roomMessage);if(!cd.allowed){ws.sendRoomMessage(targetRoomId,lang==='ar'?`⏱️ ${name} انتظر ${fmt(cd.remainingMs,'ar')} قبل إيداع جديد.`:`⏱️ ${name}, wait ${fmt(cd.remainingMs,'en')} before another deposit.`,targetRoomName);return true;}const points=await getUserPoints(user);if(points<p.amount){ws.sendRoomMessage(targetRoomId,lang==='ar'?`❌ ليس لديك نقاط كافية. نقاطك: ${points}`:`❌ Not enough points. your points: ${points}`,targetRoomName);return true;}const dep=await createBankDeposit({username:user,amount:p.amount});if(!dep.ok){ws.sendRoomMessage(targetRoomId,lang==='ar'?`❌ فشل الإيداع. السبب: ${dep.reason}`:`❌ Deposit failed. Reason: ${dep.reason}`,targetRoomName);return true;}await changeUserPoints(user,-p.amount);const final=await getUserPoints(user);ws.sendRoomMessage(targetRoomId,lang==='ar'?[`🏦 ${name} أودع ${p.amount} نقطة في البنك.`,`✅ الربح المتوقع: ${dep.deposit.profit} نقطة.`,`⏳ السحب بعد: ${dep.deposit.readyAt}`,`💰 نقاطك: ${final}`].join('\n'):[`🏦 ${name} deposited ${p.amount} points in the bank.`,`✅ expected profit: ${dep.deposit.profit} points.`,`⏳ withdraw after: ${dep.deposit.readyAt}`,`💰 your points: ${final}`].join('\n'),targetRoomName);return true;}
